name: paynest_flutter_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+27

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_screenutil:
  flutter_svg:
  pinput:
  lean_sdk_flutter: ^0.5.0
  carousel_slider:
  http:
  get:
  get_storage:
  dart_jsonwebtoken: ^2.6.2
  intl:
  flutter_local_notifications: ^9.3.2
  webview_flutter:
  url_launcher:
  xml2json:
  encrypt: ^5.0.1
  country_picker: ^2.0.12
  lottie:
  flutter_toggle_tab:
  animated_bottom_navigation_bar:
  local_auth: ^1.1.8
  shared_preferences:
  dropdown_button2:
  pdf:
  advance_pdf_viewer:
  package_info_plus:
  store_redirect:

  modal_bottom_sheet:
  collection:
  universal_platform:
  fade_shimmer:

  #Firebase Packages
  firebase_remote_config:
  firebase_core:
  firebase_messaging:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  video_player: ^2.4.7

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon.png"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/dashboard/
    - assets/svg/
    - assets/json/
    - assets/png/
    - assets/jpg/
    - assets/flags/

  fonts:
    - family: montserratBlack
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
    - family: montserratBlackItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
    - family: montserratBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
    - family: montserratExtraBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
    - family: montserratExtraBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
    - family: montserratBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
    - family: montserratExtraLight
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
    - family: montserratExtraLightItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
    - family: montserratItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
    - family: montserratLight
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
    - family: montserratLightItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
    - family: montserratMedium
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
    - family: montserratMediumItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
    - family: montserratRegular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: montserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
    - family: montserratSemiBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
    - family: montserratThin
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
    - family: montserratThinItalic
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
